[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
front_stike = "53hFFhXaWTZSjWK9fXFP4HdH3BxF9RpcAj3pB7jFakGV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/justin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
